version: '2'
services:
  celery:
    build:
      dockerfile: DockerfileCelery
      context: .
    image: celery:latest
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
    links:
      - redis_server:redis_server
  web:
    build:
      context: .
      dockerfile: DockerfileWebApi
    image: flask_api:latest
    environment:
      REDISSERVER: redis://redis_server:6379
    working_dir: /app
    ports:
      - "5000:80"
    links:
      - redis_server:redis_server
      - celery:celery
  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis_server:6379", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis_server
  redis_server:
    image: redis